### ISSUE TITLE
Issue with redfish 3.1.0 - HttpClient sessions attribute "_conn"

### ISSUE THREAD

**Issue by aj-gh** [bb-Ricardo/check_redfish#75]
I installed the dependencies for this tool yesterday and pip decided to install the recently released redfish 3.1.0 module.
With redfish 3.1.0 I then ran into a missing attribute of the HttpClient object when trying to use the session feature:
`AttributeError: 'HttpClient' object has no attribute '_conn'`

Downgrading python-redfish-library to 3.0.3 resolved my issue.
Looking into their commits it seems they replaced "http.client" with "requests".

Environment:
Ubuntu 20.04.3 LTS
Python 3.8.10
python-redfish-library via pip3 and a requirement of "redfish>=2.1.4"

Full traceback:
```
Traceback (most recent call last):
  File "./check_redfish.py", line 149, in <module>
    plugin = PluginData(args, plugin_version=__version__)
  File "/root/check_redfish/cr_module/classes/plugin.py", line 118, in __init__
    self.rf = RedfishConnection(cli_args)
  File "/root/check_redfish/cr_module/classes/redfish.py", line 59, in __init__
    self.init_connection()
  File "/root/check_redfish/cr_module/classes/redfish.py", line 333, in init_connection
    self.save_session_to_file()
  File "/root/check_redfish/cr_module/classes/redfish.py", line 248, in save_session_to_file
    connection_socket = self.connection._conn
AttributeError: 'HttpClient' object has no attribute '_conn'
```

**Comment by bb-Ricardo** [comment]
thank you for the feedback.

I will need to lock the version for now and look into upgrading the script accordingly.

**Comment by bb-Ricardo** [comment]
Hi,

I changed some code and it should now work with versions <3.1.0 and >= 3.1.0.  Can you check out the "next-release" branch and try to run it with the redfish 3.1.1 version?

Thank you.

**Comment by cmaile** [comment]
@bb-Ricardo I try the new next-release branch and the redfish version 3.1.1 and 3.1.2. 

The exception is gone now, but the check does not works:

`[CRITICAL]: Unable to connect to Host 'x.x.x.x', max retries exhausted`

With redfish version 3.0.3 works.

**Comment by bb-Ricardo** [comment]
Thank you very much for testing. I will have a look and see where this issue comes from.

**Comment by bb-Ricardo** [comment]
Hi @cmaile,

I finally got around to look into it and pushed a fix to "next-release". Can you please test if it's working now?

Thank you
